spring.application.name=issue-tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/issue_tracker
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
